### ISSUE TITLE
Error when trying to run substra config

### ISSUE THREAD

**Issue by chrisalexandrepena** [SubstraFoundation/substra#97] opened 2020-01-30 09:26 UTC
I am trying to run the `substra config http://substra-backend.node-1.com:80 -v 0.0 -u node-1 -p 'p@$swr0d44'` command on my ubuntu server 18.04.3 LTS environment. Here is the error I get :

```
Traceback (most recent call last):
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/bin/substra", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/cli/interface.py", line 256, in add_profile_to_config
    insecure=insecure,
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/config.py", line 125, in add_profile
    keyring.set_password(name, username, password)
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/keyring/core.py", line 62, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/keyring/backends/fail.py", line 24, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
```

The error gets fixed if I install the keyrings.alt dependency.

**Comment by Kelvin-M** [comment] 2020-02-05 08:16
@chrisalexandrepena This issue is caused by a wrong installation of keyrings ?
Is this still relevant to keep it as a issue as you can troubleshoot it with the traceback error from python ?

**Comment by jmorel** [comment] 2020-03-23 10:47
Closing this as a proper error message has been introduced in #121.

**Closed by jmorel** 2020-03-23 10:47 UTC
Labels: bug
